### ISSUE TITLE
[mendeley] codes not processed in user profiles

### ISSUE THREAD

**Issue by maedoc** [kochm/wp-mendeley-plugin#2]
We'd like each user to have a list of their own publications, but currently the plugin does seem to be processing the biographic info fields of user profile.

Is there a way to do this?

**Comment by kochm** [comment]
We do this by filtering by author name.

**Comment by maedoc** [comment]
On Wed, Jan 27, 2016 at 03:16:02AM -0800, Michael Koch wrote:

> We do this by filtering by author name.

I understand the filter by author name idea.

If I write `[mendeley ... filter="author=maedoc"]` in a regular post/page,
it is replaced by a list of citations, but the same text in the biographical 
text box on my profile appears as `[mendeley...]` when I view the profile.

**Comment by kochm** [comment]
No longer supported by Mende / Mendeley API
