### ISSUE TITLE
Set utf8 as CHARACTER SET in table creation

### ISSUE THREAD

**Issue by dcambie** [kochm/wp-mendeley-plugin#3]
I had issues with non-standard characters and wp-Mendeley plugin due to the default character set of my MySQL installation being latin1_swedish_ci and not utf8. Non-standard characters were shown in the publication list as question marks.

By changing the table encoding to utf8 the problem was fixed. I believe it could be useful to prevent such issues to explicitly set the CHARACTER SET to utf8 during MySQL table creation in wp-Mendeley.php at line 1204.

e.g. adding `DEFAULT CHARACTER SET=utf8;`

**Comment by kochm** [comment]
Good point. I will add the default character set settings to the create table statements in the next version of the plugin.

**Comment by kochm** [comment]
Has been included in the source.
