### ISSUE TITLE
Strange error when requesting token

### ISSUE THREAD

**Issue by dinel** [kochm/wp-mendeley-plugin#9]
When requesting a new token I get the following error from PHP:

``Notice: Undefined property: stdClass::$access_token in /srv/www/wordpress-one/public_html/wp-content/plugins/mendeleyplugin/wp-mendeley.php on line 1650``

and the plugin displays 

``Failed retrieving OAuth2 access token: {"error":"invalid_grant","error_description":"Invalid access code"}``

Strangely enough everything seems to work fine, so the error is misleading.

**Comment by kochm** [comment]
I solved the issue - and the error message is no longer displayed (v 1.3.2)
